export enum RoadType {
  Street = 1,
  PrimaryStreet = 2,
  Freeway = 3,
  Ramp = 4,
  WalkingTrail = 5,
  MajorHighway = 6,
  MinorHighway = 7,
  OffRoad = 8,
  Walkway = 9,
  PedestrianBoardwalk = 10,
  Ferry = 15,
  Stairway = 16,
  PrivateRoad = 17,
  Railroad = 18,
  RunwayTaxiway = 19,
  ParkingLotRoad = 20,
  Alley = 22,
}
